name: Deploy TuneTrace Backend to Azure ACR

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write  # Essential for OIDC login
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4AED1299D2C04CAA9208F16E2D318BEA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_614CA175BDB04D7DB7A9C5C4A9543192 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D43E42F06B844B6B9D8BBE1F39EA3069 }}

      # 1. Log in to the SongSouggest Registry
      - name: Login to ACR
        run: az acr login --name SongSouggest

      # 2. Build the Docker Image
      # This step uses your Dockerfile to bake in requirements and model weights.
      - name: Build and Push Image
        run: |
          docker build -t songsouggest.azurecr.io/backend:${{ github.sha }} .
          docker push songsouggest.azurecr.io/backend:${{ github.sha }}

      # 3. Update the Web App to pull the new container
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'song-suggest-fastapi'
          images: 'songsouggest.azurecr.io/backend:${{ github.sha }}'
